### ISSUE TITLE
string-trim is introduced at Emacs 24.4

### ISSUE THREAD

**Issue by syohex** [tuhdo/semantic-stickyfunc-enhance#1]
And it is necessary to load `subr-x` package for using it(`(require 'subr-x)`).

https://github.com/tuhdo/semantic-stickyfunc-enhance/blob/59d00f1fe2116a76af0be64ad78e8ea90936279b/stickyfunc-enhance.el#L116

**Comment by tuhdo** [comment]
@syohex Thank you for reviewing. I updated it.

**Comment by tuhdo** [comment]
Please let me know if there's more problem. Thanks.
