### ISSUE TITLE
Function at point

### ISSUE THREAD

**Issue by syl20bnr** [tuhdo/semantic-stickyfunc-enhance#2]
Maybe it's available in raw sitckyfunc. Is it possible to display the signature method of the function at point ?

**Comment by tuhdo** [comment]
That's what `semantic-idle-summary-mode` is for. See [demo](http://tuhdo.github.io/static/func_args.jpg). The modes are different: `semantic-stickyfunc-mode` displays function signature that the top line of current visible screen is in, while `semantic-idle-summary-mode` displays definition (function/variable) at point in minibuffer.

**Comment by syl20bnr** [comment]
Oh yeah, thank you !
